package com.jackwaudby.ldbcimplementations;

public enum Environments {
    PATH_TO_LDBS_SNB_IMPLEMENTATION,
    VALID_VERTEX_FILES,
    VALID_VERTEX_PROPERTIES_FILES,
    PATH_TO_JANUSGRAPH_PROPERTIES,
    PATH_TO_JANUSGRAPH_DATA,
    PATH_TO_VALIDATION_PARAMETERS
}
